name: CI
run-name: ${{ github.actor }} is learning GitHub Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Git Version
      run: git --version

    - name: Run a one-line script
      run: echo "Hello, Fellows!"
